import type { Metadata } from "next";
import "react-perfect-scrollbar/dist/css/styles.css";
import 'react-toastify/dist/ReactToastify.css';
import "react-responsive-modal/styles.css";
import "swiper/css";
import "swiper/css/navigation";
import "../public/assets/css/main.css";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Nest - Redux NextJS eCommerce Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}

